// <auto-generated />
namespace AnubisDBMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AnubisDBMS16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnubisDBMS16));
        
        string IMigrationMetadata.Id
        {
            get { return "201911260150326_AnubisDBMS1.6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
