// <auto-generated />
namespace AnubisDBMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class AnubisDBMS10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnubisDBMS10));
        
        string IMigrationMetadata.Id
        {
            get { return "201911141928281_AnubisDBMS1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
